##
## EPITECH PROJECT
##
## File description:
## Makefile
##

all:
				ghc DoOp.hs -o doop

clean:
				rm -f doop

fclean:			clean
				rm -f DoOp.hi doop DoOp.o

re:             fclean all

.PHONY:         all fclean clean re
